create  schema speedhome;

create table categories (id integer generated by default as identity, name varchar(255), primary key (id));

create table properties (id integer generated by default as identity, address varchar(255), approved boolean not null, city varchar(255), pincode varchar(255), state varchar(255), category_id integer, user_id integer, primary key (id));

create table roles (id integer generated by default as identity, name varchar(255), primary key (id));

create table users (id integer generated by default as identity, enabled boolean not null, password varchar(255), username varchar(255), primary key (id));


create table users_roles (users_id integer not null, roles_id integer not null);


 alter table properties add constraint FK2am91onrpg0i2jg44flrxsvx8 foreign key (category_id) references categories;
 alter table properties add constraint FKtnyxik10x9mx26017sjnuo2nw foreign key (user_id) references users;
 alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles;
 alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users;

